// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1B919bZtSGypW0J4bfzmosCAa6v--k_s',
    appId: '1:1090205478306:web:24c915db422ce4d0c096fb',
    messagingSenderId: '1090205478306',
    projectId: 'expense-tracker-siku69',
    authDomain: 'expense-tracker-siku69.firebaseapp.com',
    storageBucket: 'expense-tracker-siku69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwy7YygR7ptxISqBsmCGgO0sXhRyAMXvk',
    appId: '1:1090205478306:android:d4aaffea02535bc0c096fb',
    messagingSenderId: '1090205478306',
    projectId: 'expense-tracker-siku69',
    storageBucket: 'expense-tracker-siku69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5P49FP3P1KXFwyznUFZQNQ2GwQJk5PEc',
    appId: '1:1090205478306:ios:263a5cc42571ae2dc096fb',
    messagingSenderId: '1090205478306',
    projectId: 'expense-tracker-siku69',
    storageBucket: 'expense-tracker-siku69.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5P49FP3P1KXFwyznUFZQNQ2GwQJk5PEc',
    appId: '1:1090205478306:ios:263a5cc42571ae2dc096fb',
    messagingSenderId: '1090205478306',
    projectId: 'expense-tracker-siku69',
    storageBucket: 'expense-tracker-siku69.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1B919bZtSGypW0J4bfzmosCAa6v--k_s',
    appId: '1:1090205478306:web:d58019bfb017a94bc096fb',
    messagingSenderId: '1090205478306',
    projectId: 'expense-tracker-siku69',
    authDomain: 'expense-tracker-siku69.firebaseapp.com',
    storageBucket: 'expense-tracker-siku69.firebasestorage.app',
  );
}
